### ISSUE TITLE
publicKeyToHex is not a function

### ISSUE THREAD

**Issue by Javamr123** [solana-labs/solana-solidity.js#12] opened 2021-11-12 07:44 UTC
const address = publicKeyToHex(payer.publicKey);
                    ^

TypeError: publicKeyToHex is not a function

**Comment by Javamr123** [comment] 2021-11-12 07:44
help!

**Comment by jordansexton** [comment] 2021-11-14 17:08
I believe the issue is that the `@solana/solidity` npm package needs to be published again, there have been API changes the readme usage example depends on. cc @seanyoung

**Comment by seanyoung** [comment] 2021-11-15 16:50
I've just published a new version: 0.0.17. It should be fixed in this.

**Closed** 2021-12-15 00:41 UTC
